# Loads some sample pod and service definitions to the master for launching by kubectl
# See files in samples directory for details
# Assumes the cluster is up and configured as per the defaults, as do the samples

---
- hosts: master
  remote_user: vagrant
  become: yes

  vars:
    - pod_directory: /usr/local/kubernetes/pods
    - svc_directory: /usr/local/kubernetes/svc

  tasks:
    - name: copy sample pod definitions
      copy:
        dest: "{{ pod_directory }}"
        src: "{{ item }}"
      with_items:
        - samples/couchpod-pv.yml
        - samples/prefserverpod.yml
    - name: copy sample service definitions
      copy:
        dest: "{{ svc_directory }}"
        src: "{{ item }}"
      with_items:
        - samples/couchsvc.yml
        - samples/prefserversvc.yml
