---
# tasks file for ansible-kubernetes-atomic-nfs-client

# Atomic Host already has nfs utils (and no package manager...)

- name: install nfs-utils
  yum:
    name: nfs-utils
    state: latest

- name: create a directory for the nfs mount
  file:
    dest: "{{ kube_node_nfs_mount_directory }}"
    state: directory

- name: permanently mount the nfs directory
  mount:
    name: "{{ kube_node_nfs_mount_directory }}"
    src: "{{ kube_nfs_ip }}:{{ kube_nfs_storage_directory }}"
    fstype: nfs4
    state: mounted
