---
# tasks file for ansible-kubernetes-atomic-busybox

- name: create a directory for Pod definitions
  file:
    dest: /usr/local/kubernetes/pods
    state: directory
- name: copy busybox configs into place
  template:
    dest: /usr/local/kubernetes/pods/{{ item }}.yml
    src: busybox.j2
  with_items:
    - "{{ busybox_pod_names }}"
- name: launch busybox pods
  command: kubectl create -f /usr/local/kubernetes/pods/{{ item }}.yml
  with_items:
    - "{{ busybox_pod_names }}"
