---
# tasks file for ansible-kubernetes-atomic-node

# - name: upgrade the atomic host
#   command: atomic host upgrade

# - name: restart atomic host if upgraded
#   command: systemctl reboot

- name: template Docker config file into place
  template:
    dest: /etc/sysconfig/docker
    src: docker.j2
    backup: yes

- name: set device name used for Vagrant private network as a fact, for use when configuring flannel
  shell: ip addr | grep 192.168.87 | sed -n -e 's/^.*global //p'
  register: vagrant_private_network_device_name

- name: template flanneld config file into place
  template:
    dest: /etc/sysconfig/flanneld
    src: flanneld.j2
    backup: yes

- name: make directory for custom Docker service definition
  file:
    dest: /etc/systemd/system/docker.service.d/
    state: directory

- name: copy custom Docker service definition into place
  copy:
    dest: /etc/systemd/system/docker.service.d/10-flanneld-network.conf
    src: 10-flanneld-network.conf
    backup: yes

- name: template kubelet config into place
  template:
    dest: /etc/kubernetes/kubelet
    src: kubelet.j2
    backup: yes

- name: template kubernetes node config into place
  template:
    dest: /etc/kubernetes/config
    src: kubernetes_node.j2
    backup: yes

- name: reload systemd
  command: systemctl daemon-reload

- name: ensure kubernetes node services enabled and running
  service:
    name: "{{ item }}"
    enabled: yes
    state: restarted
  with_items:
      - docker
      - flanneld
      - kubelet
      - kube-proxy

- name: put SELinux into permissive mode
  command: setenforce 0
